name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-ci
          chmod 600 ~/.ssh/github-ci
          ssh-keyscan -H 207.154.240.145 >> ~/.ssh/known_hosts

      - name: Deploy to droplet
        run: |
          ssh -i ~/.ssh/github-ci mariogl@207.154.240.145 << 'EOF'
            cd /srv/trp-journey-entregueitor-api
            git pull origin main
            npm install --omit=dev
            npm start
          EOF
